2024-12-15 18:16:33,581 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:16:33,762 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:16:33,908 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:38:03,156 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:38:03,159 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:38:05,673 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:38:05,675 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:39:04,931 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:39:06,482 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:39:07,108 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:39:14,915 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:39:15,894 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:39:16,025 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:39:16,096 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:39:16,309 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:39:16,482 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:39:16,679 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:46:51,722 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:46:51,724 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:46:53,826 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:46:53,919 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:46:54,194 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:46:54,259 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:46:54,471 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:46:54,653 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:46:55,211 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:46:55,385 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:46:55,524 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:47:37,950 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:47:38,837 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is invalid.
2024-12-15 18:48:45,261 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:48:46,744 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:48:47,875 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:18,928 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:20,160 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:20,862 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:21,891 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:22,617 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:22,798 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:22,894 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:23,024 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:23,422 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:25,351 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:26,152 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 18:55:26,382 - app - ERROR - CSRF error: 400 Bad Request: The CSRF token is missing.
2024-12-15 20:52:08,251 - app - ERROR - CSRF error: 400 Bad Request: The CSRF session token is missing.
2024-12-15 20:59:24,553 - app - ERROR - CSRF error: 400 Bad Request: The CSRF session token is missing.
2024-12-15 21:17:00,717 - app.modules.dataset.routes - ERROR - Exception while create dataset data in Zenodo 'DataSet' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/app/modules/dataset/routes.py", line 83, in create_dataset
    fakenodo_response_json = fakenodo_service.create_new_deposition(dataset)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/fakenodo/services.py", line 38, in create_new_deposition
    "title": metadata.get("title", "Untitled"),
             ^^^^^^^^^^^^
AttributeError: 'DataSet' object has no attribute 'get'
2024-12-15 21:17:00,717 - app.modules.dataset.routes - ERROR - Exception while create dataset data in Zenodo 'DataSet' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/app/modules/dataset/routes.py", line 83, in create_dataset
    fakenodo_response_json = fakenodo_service.create_new_deposition(dataset)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/fakenodo/services.py", line 38, in create_new_deposition
    "title": metadata.get("title", "Untitled"),
             ^^^^^^^^^^^^
AttributeError: 'DataSet' object has no attribute 'get'
2024-12-15 21:17:49,911 - app.modules.dataset.routes - ERROR - Exception while create dataset data in Zenodo 'DataSet' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/app/modules/dataset/routes.py", line 83, in create_dataset
    fakenodo_response_json = fakenodo_service.create_new_deposition(dataset)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/fakenodo/services.py", line 38, in create_new_deposition
    "title": metadata.get("title", "Untitled"),
             ^^^^^^^^^^^^
AttributeError: 'DataSet' object has no attribute 'get'
2024-12-15 21:17:49,911 - app.modules.dataset.routes - ERROR - Exception while create dataset data in Zenodo 'DataSet' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/app/modules/dataset/routes.py", line 83, in create_dataset
    fakenodo_response_json = fakenodo_service.create_new_deposition(dataset)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/fakenodo/services.py", line 38, in create_new_deposition
    "title": metadata.get("title", "Untitled"),
             ^^^^^^^^^^^^
AttributeError: 'DataSet' object has no attribute 'get'
2024-12-15 21:18:51,064 - app.modules.dataset.routes - ERROR - Exception while create dataset data in Zenodo 'DataSet' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/app/modules/dataset/routes.py", line 83, in create_dataset
    fakenodo_response_json = fakenodo_service.create_new_deposition(dataset)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/fakenodo/services.py", line 38, in create_new_deposition
    "title": metadata.get("title", "Untitled"),
             ^^^^^^^^^^^^
AttributeError: 'DataSet' object has no attribute 'get'
2024-12-15 21:18:51,064 - app.modules.dataset.routes - ERROR - Exception while create dataset data in Zenodo 'DataSet' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/app/modules/dataset/routes.py", line 83, in create_dataset
    fakenodo_response_json = fakenodo_service.create_new_deposition(dataset)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/fakenodo/services.py", line 38, in create_new_deposition
    "title": metadata.get("title", "Untitled"),
             ^^^^^^^^^^^^
AttributeError: 'DataSet' object has no attribute 'get'
2024-12-15 21:22:58,988 - app - ERROR - CSRF error: 400 Bad Request: The CSRF session token is missing.
2024-12-15 21:23:00,483 - app - ERROR - CSRF error: 400 Bad Request: The CSRF session token is missing.
2024-12-15 21:23:00,554 - app - ERROR - CSRF error: 400 Bad Request: The CSRF session token is missing.
2024-12-15 21:23:00,750 - app - ERROR - CSRF error: 400 Bad Request: The CSRF session token is missing.
2024-12-15 21:23:01,316 - app - ERROR - CSRF error: 400 Bad Request: The CSRF session token is missing.
2024-12-15 21:23:01,730 - app - ERROR - CSRF error: 400 Bad Request: The CSRF session token is missing.
2024-12-15 21:23:01,948 - app - ERROR - CSRF error: 400 Bad Request: The CSRF session token is missing.
2024-12-15 21:23:02,115 - app - ERROR - CSRF error: 400 Bad Request: The CSRF session token is missing.
2024-12-15 21:23:02,276 - app - ERROR - CSRF error: 400 Bad Request: The CSRF session token is missing.
2024-12-15 21:23:44,712 - app.modules.dataset.routes - ERROR - Exception while create dataset data in Zenodo 'DataSet' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/app/modules/dataset/routes.py", line 83, in create_dataset
    fakenodo_response_json = fakenodo_service.create_new_deposition(dataset)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/fakenodo/services.py", line 38, in create_new_deposition
    "title": metadata.get("title", "Untitled"),
             ^^^^^^^^^^^^
AttributeError: 'DataSet' object has no attribute 'get'
2024-12-15 21:23:44,712 - app.modules.dataset.routes - ERROR - Exception while create dataset data in Zenodo 'DataSet' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/app/modules/dataset/routes.py", line 83, in create_dataset
    fakenodo_response_json = fakenodo_service.create_new_deposition(dataset)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/fakenodo/services.py", line 38, in create_new_deposition
    "title": metadata.get("title", "Untitled"),
             ^^^^^^^^^^^^
AttributeError: 'DataSet' object has no attribute 'get'
